---
language: java

env:
  - TERM=dumb

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script: python -m py_compile extra/datadog/plog.py

after_success:
  - ./gradlew cobertura coveralls
