---
language: java

env:
  - TERM=dumb

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - ./gradlew check --info
  - python -m py_compile third-party/datadog/plog.py

after_success:
  - ./gradlew cobertura coveralls
